version: '2'
services:
  kong:
    image: mashape/kong
    depends_on:
      - cassandra
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    security_opt:
      - seccomp:unconfined
  cassandra:
    image: cassandra:2.2.5
    ports:
      - 9042:9042
  go-api:
    build: go-api
    ports:
      - 8000:8000
  rails-api:
    build: rails-api
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file: rails-api/.env
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: rails-api
      POSTGRES_DB: rails-api_production
    env_file: rails-api/.env
